### ISSUE TITLE
[Bug] grad_accum_steps has no effect on training

### ISSUE THREAD

**Issue by FerrahWolfeh** [coqui-ai/Trainer#120]
### Describe the bug

Supposedly, setting a value to the `--grad_accum_steps` option should decrease the needed steps to complete an epoch by simulating a higher batch size, however, setting it to any value does absolutely nothing on training speed or the total step counter.

### To Reproduce

1. Start training with a `batch_size=8` using the recipe `train_vits_tts_phonemes.py --grad_accum_steps=16` or add the value direcly to `Trainer()`
2. See number of steps per epoch
3. change `--grad_accum_steps` to another value
4. Number of steps required doesn't change, therefore, the effective batch size hasn't changed

### Expected behavior

Assuming the `batch_size=8` and `grad_accum_steps=8`, an epoch that has 6400 steps to complete should reduce the number of steps to 100 while having an effective batch size of 64 (8*8) during training.

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 2060"
        ],
        "available": true,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1+cu117",
        "Trainer": "v0.0.29",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "",
        "python": "3.10.12",
        "version": "#1 ZEN SMP PREEMPT_DYNAMIC Wed, 02 Aug 2023 10:40:11 +0000"
    }
}
```

**Comment by erogol** [comment]
Logging is misleading. it prints accumulation steps too. But you see no grad norm since those steps are not immediately used for stepping the optimizer.

**Comment by FerrahWolfeh** [comment]
Oh, so that's why `grad_norm` only appears sometimes? 
Now I think the only thing that needs to be checked out is the logging/step counter. I'm currently training at batch 4 and grad_accum 4, yet it shows the steps for a effective batch size of 4, so it becomes a little confusing once in a while.

But thanks anyways
