### ISSUE TITLE
[Bug] Cannot run with Python 3.12.4

### ISSUE THREAD

**Issue by Giger22** [coqui-ai/Trainer#146]
### Describe the bug

Can you change it?
"ERROR: Package 'trainer' requires a different Python: 3.12.4 not in '<3.12,>=3.6.0'
==> ERROR: A failure occurred in package()."

### To Reproduce

All it takes is to have the 3.12.4 python version

### Environment

```shell
3.12.4
```

**Comment by eginhard** [comment]
You can install [our fork](https://github.com/idiap/coqui-ai-TTS) with `pip install coqui-tts`, it supports Python 3.12. Or if you just need the trainer `pip install coqui-tts-trainer`

**Comment by Giger22** [comment]
Ok, that worked!

**Comment by mmcc1** [comment]
Can we get an updated build?
