### ISSUE TITLE
[Bug] Misleading python version constraint message

### ISSUE THREAD

**Issue by mweinelt** [coqui-ai/Trainer#22]
### Describe the bug

Seems like you wanted to say `< 3.10` but wrote `<= 3.10`, at least the latter would allow `3.10`, but not `3.10.2`.

https://github.com/coqui-ai/Trainer/blob/45a5604cc23dba2ecebf2879d2e1dcc1be64ac38/setup.py#L33-L39

### To Reproduce

Building coqui-trainer with python 3.10.2

### Expected behavior

Clarification whether `<` or `<=` is the intended constraint.

### Logs

```shell
>   RuntimeError: Coqui-Trainer requires python >= 3.6 and <=3.10 but your Python version is 3.10.2 (main, Jan 13 2022, 19:06:22) [GCC 10.3.0]
```

### Environment

```shell
- Version 0.0.5
- Python 3.10.2
```

**Comment by erogol** [comment]
Should have been corrected with the last version
